-- require("plugins_dir.telescope")
-- require("plugins_dir.lsp-kind")
-- require("plugins_dir.treesitter")
-- require("plugins_dir.nvim-cmp")
-- require("plugins_dir.lua-snip")
-- require("plugins_dir.formatter")
-- require("plugins_dir.lualine")
-- require("plugins_dir.gitsigns")
-- require("plugins_dir.trouble")
require("plugins_dir.colorscheme")
-- require("plugins_dir.nvim-autopairs")
-- require("plugins_dir.todo-comments")
-- require("plugins_dir.debugger")

-- require("plugins_dir.fzf-lua")
