#!/bin/bash

# -------- test block ---------#
super + a
	focus mode_toggle


#  ------ programs  -------- # 

# open st terminal
super + Return
	st

# open st terminal with same direcotry
super + shift + Return
	samedir

super + d 
	rofimenu

# STOP/HIDE Everything
super + shift + Delete
		amixer sset Master mute &  bspc desktop -f '^16' & st -e htop & st -e $FILE & xdo hide -N Polybar

super + b
		if [ -z "$(xdotool search --onlyvisible --name Polybar)" ]; then \ 
			xdo show -N Polybar; \ 
		else \ 
			xdo hide -N Polybar; \ 
		fi

# close and kill
super + {_,shift + }q
	bspc node -{c,k}

# Show Selection
super + Insert
	showclip

super + shift + w
		st -e nmtui

super + {w, r, x}
		{$BROWSER,$($TERMINAL -e $FILE)}
	
# lock
super + x 
	bspc desktop -f '^16' &amixer sset Master mute & i3lock -e -f -c 000000 & xset dpms force off
super + shift + x
	prompt "Shutdown Computer?" "$(wifi)"
# super + shift + a
	# wifi

super + bracket{left,right}
	bspc desktop -f {prev,next}.local


super + v
	st -e $EDITOR -c "VimwikiIndex"
# reload config (bspwmrc and sxhkdrc)  # 

super + {F5, F9, F10 F12}
	{netrefresh, dmenumount, dmenumount, wifi}


super + shift + r
        pkill -USR1 -x sxhkd

super + shift + e
        bspc wm -r





#  ------ brightness  -------- # 


XF86MonBrightnessUp
    br +10

shift + XF86MonBrightnessUp
    br +5

XF86MonBrightnessDown
    br -10

shift + XF86MonBrightnessDown
    br -5


#  ------------ bspwm hotkeys ------------ # 

super + shift + Escape
		bspc quit

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}


# alternate between the tiled and monocle layout
super + Tab
	bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest node
# super + g
# 	bspc node -s biggest


# state/flags


# floating toggle
super + shift + space
	if [ -z "$(bspc query -N -n focused.floating)" ]; then \
        bspc node focused -t floating; \
    else \
        bspc node focused -t tiled; \
    fi
super + f
	if [ -z "$(bspc query -N -n focused.fullscreen)" ]; then \
        bspc node focused -t fullscreen; \
    else \
        bspc node focused -t tiled; \
    fi


# super + i
# 	htop

# set the window state
# super + {d,shift + d, s}
# 	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

# focus/swap

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop
super + {_,shift + }c
	bspc node -f {next,prev}.local

# focus the next/previous desktop in the current monitor
# super + bracket{left,right}
# 	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

# preselect ( select the direction you want the window to be opened in )

# preselect the direction
super + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

# move/resize

# expand a window by moving one of its side outward
super + alt + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}


super + m
  bspc desktop -l next  # idk what this does 


# -------------- take screenshots ------------- #


#fullscreen screenshot save

super + Print
     maim "/home/$USER/Pictures/$(date).jpg"

#cropped save
super + shift + x
      maim --select "/home/$USER/Pictures/$(date).jpg"

#  clipboard fullscreen
super + u
     maim | xclip -selection clipboard -t image/png

# clipboard cropped
super + shift + u
    maim --select | xclip -selection clipboard -t image/png


# ------------ volumes ----------------------#

XF86AudioRaiseVolume
    amixer sset Master 5%+
XF86AudioLowerVolume
	amixer sset Master 5%-
XF86AudioMute
    amixer sset Master mute