#! /bin/sh

sxhkd &

# polybar

refreshp &

# compositing and wallpaper 

exec $(pgrep redshift && pkill -TERM redshift & redshift-gtk) &

# exec redshift &

picom  & $(bspc config focus_follows_pointer true) &

feh --bg-fill ~/Pictures/wall/bg.jpg &
xrdb merge ~/.Xresources &  # (terminal theme)

bspc monitor -d I II III IV V VI VII VIII IX X XI XII XIII XIV XV XVI

bspc config border_width         2
bspc config window_gap          7
bsp config presel_feedback_color "#ffffff" 
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config top_padding 20

# border colors 
bspc config focused_border_color "#83a598"
bspc config normal_border_color "#454849"


